const AuthenticationActionTypes = {
    SIGNIN_TOGGLE : 'SIGNIN_TOGGLE',
    REQUEST_OTP_START : 'REQUEST_OTP_START',
    REQUEST_OTP_SUCCESS : 'REQUEST_OTP_SUCCESS',
    REQUEST_OTP_ERROR : 'REQUEST_OTP_ERROR',
    OTP_SUBMIT_START : 'OTP_SUBMIT_START',
    OTP_SUBMIT_SUCCESS : 'OTP_SUBMIT_SUCCESS',
    OTP_SUBMIT_ERROR : 'OTP_SUBMIT_ERROR',
    CLEAR_PROFILENTOKEN : 'CLEAR_PROFILENTOKEN',
    PROFILE_MODIFY_START : 'PROFILE_MODIFY_START',
    PROFILE_MODIFY_SUCCESS : 'PROFILE_MODIFY_SUCCESS',
    PROFILE_MODIFY_ERROR : 'PROFILE_MODIFY_ERROR',
    PROFILE_MODIFY_CLEAR : 'PROFILE_MODIFY_CLEAR',
    REQUEST_PROFILE_START : 'REQUEST_PROFILE_START',
    REQUEST_PROFILE_SUCCESS : 'REQUEST_PROFILE_SUCCESS',
    REQUEST_PROFILE_ERROR : 'REQUEST_PROFILE_ERROR'
}

export default AuthenticationActionTypes