const orderActionTypes = {
    PLACE_ORDER_START : 'PLACE_ORDER_START',
    PLACE_ORDER_SUCCESS : 'PLACE_ORDER_SUCCESS',
    PLACE_ORDER_FAILURE : 'PLACE_ORDER_FAILURE',
    RESET_PLACE_ORDER : 'RESET_PLACE_ORDER',
    FETCH_ORDER_START : 'FETCH_ORDER_START',
    FETCH_ORDER_SUCCESS :'FETCH_ORDER_SUCCESS',
    FETCH_ORDER_ERROR : 'FETCH_ORDER_ERROR',
    CLEAR_ORDER : 'CLEAR_ORDER' 
}

export default orderActionTypes