const AddressActionTypes = {
  FETCH_ADDRESS_START : 'FETCH_ADDRESS_START',
  FETCH_ADDRESS_SUCCESS : 'FETCH_ADDRESS_SUCCESS',
  FETCH_ADDRESS_ERROR : 'FETCH_ADDRESS_ERROR',
  SUBMIT_ADDRESS_START : 'SUBMIT_ADDRESS_START',
  SUBMIT_ADDRESS_SUCCESS : 'SUBMIT_ADDRESS_SUCCESS',
  SUBMIT_ADDRESS_ERROR : 'SUBMIT_ADDRESS_ERROR',
  DELETE_ADDRESS_START : 'DELETE_ADDRESS_START',
  DELETE_ADDRESS_SUCCESS : 'DELETE_ADDRESS_SUCCESS',
  DELETE_ADDRESS_ERROR : 'DELETE_ADDRESS_ERROR',
  MODIFY_ADDRESS_START : 'MODIFY_ADDRESS_START',
  MODIFY_ADDRESS_SUCCESS : 'MODIFY_ADDRESS_SUCCESS',
  MODIFY_ADDRESS_ERROR : 'MODIFY_ADDRESS_ERROR',
  RESET_ADDRESS_STATE : 'RESET_ADDRESS_STATE' 
}

export default AddressActionTypes